services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always

        ports:
            - "5432:5432"

        environment :
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: online-store

        volumes:
            - /var/db/postgres/online-store

volumes:
    postgres:
        name: db